//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Scripts/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""BaseMovement"",
            ""id"": ""b8892afb-b52f-422f-9ad0-cc1b4910c7f5"",
            ""actions"": [
                {
                    ""name"": ""Walk"",
                    ""type"": ""Value"",
                    ""id"": ""185f90c9-d7b6-4bcc-a8fd-12dbdfbdb4c3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Value"",
                    ""id"": ""534c6b88-d394-474a-ada0-df6c08386dd3"",
                    ""expectedControlType"": ""Integer"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""23ab2b23-a3bd-4b7c-9fda-0f975bda451a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cover"",
                    ""type"": ""Button"",
                    ""id"": ""e485ba34-cbc7-46ed-a9ed-775e57ae861a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""VaultStanding"",
                    ""type"": ""Button"",
                    ""id"": ""a9ac996f-12ec-4a6c-8c6f-affb260c5655"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AimDown"",
                    ""type"": ""Button"",
                    ""id"": ""7583a909-e318-4e7e-a0b5-841a70577b63"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fire"",
                    ""type"": ""Button"",
                    ""id"": ""0f78f087-d736-403a-9964-704e02efab9d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""ac8f92c1-6317-421c-8ce3-d402383d0d19"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""WeaponScroll"",
                    ""type"": ""Value"",
                    ""id"": ""91747b16-d1f7-406f-8861-895ffc5f7289"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""83171e98-9434-482b-aafb-39e34a079d21"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""9ec11344-a748-4a29-91a9-68702e051749"",
                    ""path"": ""2DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""20043ee1-e500-4a8c-abba-c91817779cc9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""bcb32f24-0ec0-4486-aa69-eeeb5af8e679"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""0b6ce123-c0ba-4dd4-8dfc-5feb283c5743"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""476c19d1-7732-49a0-b92c-b9be6be113cc"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""253cc40b-1d2b-47ad-889f-5388d47a5583"",
                    ""path"": ""2DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""adf60b7d-bdf5-40c4-91e9-3c6026fb2985"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""9f0f3c45-14b4-4660-bbb5-67f29d29d140"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""72616471-c845-49b2-bcef-a3ac69f39d72"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""90525671-1c00-4be8-a4d9-addba6fea6fa"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""cb1f4ad0-82a0-4e93-8b37-de85e1edff7c"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8bdb0713-5afd-4d5b-a80e-705980924281"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3393a0c-179f-4a0e-a64d-ea3fbd29dd4a"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65e8bad5-8a6a-4a74-ae83-c75dede786ad"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa003c7e-3806-48ad-a431-232f82e95ddf"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VaultStanding"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2bd2227d-bce6-42cf-b1e2-0854e5932ae5"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""510463d9-5396-49c8-a01d-02784b806fad"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86db210a-1998-4ab1-a163-b3482f90fd62"",
                    ""path"": ""<Pointer>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00670e86-67e0-47e7-abd1-4e4cde59a38d"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""691d4a6b-7027-440f-9a93-9dd7769b905f"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Cover"",
            ""id"": ""de8e0673-8fe4-4f30-8cb9-b030dc3223e4"",
            ""actions"": [
                {
                    ""name"": ""CoverMovement"",
                    ""type"": ""Value"",
                    ""id"": ""e6bf8770-cea6-4ac7-95e4-c14ba6205493"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Exit Cover"",
                    ""type"": ""Button"",
                    ""id"": ""1e568549-a301-44cd-93d2-4b9b6f2d43c2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""VaultInCover"",
                    ""type"": ""Button"",
                    ""id"": ""5e83045e-467d-4898-8238-85e182877427"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CoverAim"",
                    ""type"": ""Button"",
                    ""id"": ""f41fbd15-2015-498a-965a-24607be80420"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CoverLook"",
                    ""type"": ""Value"",
                    ""id"": ""f1078623-4a81-4892-9064-135252331eb4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CoverShoot"",
                    ""type"": ""Button"",
                    ""id"": ""d3f074b0-7126-4e3e-9b9f-be171cb6099f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""b158faac-bf51-459e-b9fc-f53bfaef3562"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CoverMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2cc8874d-21de-42c8-ba63-4a6be32810af"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CoverMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c213931d-869d-41ad-92b0-24a084d0dc3d"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CoverMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d56550bc-1b6c-4fff-b418-92f4f8ad3aec"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CoverMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a2c31f86-6aa5-4ae7-9cd8-29b2f91a7602"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CoverMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""47730bac-5d00-4a0c-bdc2-c4d1192519bd"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CoverMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""281bcd35-22f7-4e5c-a847-d186e2f86582"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CoverMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""409062a8-0d33-4ce9-80ea-822cc7562c21"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CoverMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2a5bcc3a-eaa9-48a6-8bf8-423429b187e7"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CoverMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""18718f3f-4df9-4dd8-8ee9-249db528b880"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CoverMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e9c7efdc-2f33-47c3-8847-df5698bc3f28"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Exit Cover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dead8958-e2f6-4e5e-a3d1-9a4c5c95493b"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VaultInCover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a91b062-4a83-4e8d-b7a7-0b15329356ee"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CoverAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""130940f5-7493-4637-b338-29ba46a5e3e3"",
                    ""path"": ""<Pointer>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CoverLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7cbe6ce2-e8a1-46c2-9042-ff899895c895"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CoverShoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // BaseMovement
        m_BaseMovement = asset.FindActionMap("BaseMovement", throwIfNotFound: true);
        m_BaseMovement_Walk = m_BaseMovement.FindAction("Walk", throwIfNotFound: true);
        m_BaseMovement_Sprint = m_BaseMovement.FindAction("Sprint", throwIfNotFound: true);
        m_BaseMovement_Crouch = m_BaseMovement.FindAction("Crouch", throwIfNotFound: true);
        m_BaseMovement_Cover = m_BaseMovement.FindAction("Cover", throwIfNotFound: true);
        m_BaseMovement_VaultStanding = m_BaseMovement.FindAction("VaultStanding", throwIfNotFound: true);
        m_BaseMovement_AimDown = m_BaseMovement.FindAction("AimDown", throwIfNotFound: true);
        m_BaseMovement_Fire = m_BaseMovement.FindAction("Fire", throwIfNotFound: true);
        m_BaseMovement_Look = m_BaseMovement.FindAction("Look", throwIfNotFound: true);
        m_BaseMovement_WeaponScroll = m_BaseMovement.FindAction("WeaponScroll", throwIfNotFound: true);
        m_BaseMovement_Reload = m_BaseMovement.FindAction("Reload", throwIfNotFound: true);
        // Cover
        m_Cover = asset.FindActionMap("Cover", throwIfNotFound: true);
        m_Cover_CoverMovement = m_Cover.FindAction("CoverMovement", throwIfNotFound: true);
        m_Cover_ExitCover = m_Cover.FindAction("Exit Cover", throwIfNotFound: true);
        m_Cover_VaultInCover = m_Cover.FindAction("VaultInCover", throwIfNotFound: true);
        m_Cover_CoverAim = m_Cover.FindAction("CoverAim", throwIfNotFound: true);
        m_Cover_CoverLook = m_Cover.FindAction("CoverLook", throwIfNotFound: true);
        m_Cover_CoverShoot = m_Cover.FindAction("CoverShoot", throwIfNotFound: true);
    }

    ~@PlayerControls()
    {
        UnityEngine.Debug.Assert(!m_BaseMovement.enabled, "This will cause a leak and performance issues, PlayerControls.BaseMovement.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Cover.enabled, "This will cause a leak and performance issues, PlayerControls.Cover.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // BaseMovement
    private readonly InputActionMap m_BaseMovement;
    private List<IBaseMovementActions> m_BaseMovementActionsCallbackInterfaces = new List<IBaseMovementActions>();
    private readonly InputAction m_BaseMovement_Walk;
    private readonly InputAction m_BaseMovement_Sprint;
    private readonly InputAction m_BaseMovement_Crouch;
    private readonly InputAction m_BaseMovement_Cover;
    private readonly InputAction m_BaseMovement_VaultStanding;
    private readonly InputAction m_BaseMovement_AimDown;
    private readonly InputAction m_BaseMovement_Fire;
    private readonly InputAction m_BaseMovement_Look;
    private readonly InputAction m_BaseMovement_WeaponScroll;
    private readonly InputAction m_BaseMovement_Reload;
    public struct BaseMovementActions
    {
        private @PlayerControls m_Wrapper;
        public BaseMovementActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Walk => m_Wrapper.m_BaseMovement_Walk;
        public InputAction @Sprint => m_Wrapper.m_BaseMovement_Sprint;
        public InputAction @Crouch => m_Wrapper.m_BaseMovement_Crouch;
        public InputAction @Cover => m_Wrapper.m_BaseMovement_Cover;
        public InputAction @VaultStanding => m_Wrapper.m_BaseMovement_VaultStanding;
        public InputAction @AimDown => m_Wrapper.m_BaseMovement_AimDown;
        public InputAction @Fire => m_Wrapper.m_BaseMovement_Fire;
        public InputAction @Look => m_Wrapper.m_BaseMovement_Look;
        public InputAction @WeaponScroll => m_Wrapper.m_BaseMovement_WeaponScroll;
        public InputAction @Reload => m_Wrapper.m_BaseMovement_Reload;
        public InputActionMap Get() { return m_Wrapper.m_BaseMovement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BaseMovementActions set) { return set.Get(); }
        public void AddCallbacks(IBaseMovementActions instance)
        {
            if (instance == null || m_Wrapper.m_BaseMovementActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BaseMovementActionsCallbackInterfaces.Add(instance);
            @Walk.started += instance.OnWalk;
            @Walk.performed += instance.OnWalk;
            @Walk.canceled += instance.OnWalk;
            @Sprint.started += instance.OnSprint;
            @Sprint.performed += instance.OnSprint;
            @Sprint.canceled += instance.OnSprint;
            @Crouch.started += instance.OnCrouch;
            @Crouch.performed += instance.OnCrouch;
            @Crouch.canceled += instance.OnCrouch;
            @Cover.started += instance.OnCover;
            @Cover.performed += instance.OnCover;
            @Cover.canceled += instance.OnCover;
            @VaultStanding.started += instance.OnVaultStanding;
            @VaultStanding.performed += instance.OnVaultStanding;
            @VaultStanding.canceled += instance.OnVaultStanding;
            @AimDown.started += instance.OnAimDown;
            @AimDown.performed += instance.OnAimDown;
            @AimDown.canceled += instance.OnAimDown;
            @Fire.started += instance.OnFire;
            @Fire.performed += instance.OnFire;
            @Fire.canceled += instance.OnFire;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @WeaponScroll.started += instance.OnWeaponScroll;
            @WeaponScroll.performed += instance.OnWeaponScroll;
            @WeaponScroll.canceled += instance.OnWeaponScroll;
            @Reload.started += instance.OnReload;
            @Reload.performed += instance.OnReload;
            @Reload.canceled += instance.OnReload;
        }

        private void UnregisterCallbacks(IBaseMovementActions instance)
        {
            @Walk.started -= instance.OnWalk;
            @Walk.performed -= instance.OnWalk;
            @Walk.canceled -= instance.OnWalk;
            @Sprint.started -= instance.OnSprint;
            @Sprint.performed -= instance.OnSprint;
            @Sprint.canceled -= instance.OnSprint;
            @Crouch.started -= instance.OnCrouch;
            @Crouch.performed -= instance.OnCrouch;
            @Crouch.canceled -= instance.OnCrouch;
            @Cover.started -= instance.OnCover;
            @Cover.performed -= instance.OnCover;
            @Cover.canceled -= instance.OnCover;
            @VaultStanding.started -= instance.OnVaultStanding;
            @VaultStanding.performed -= instance.OnVaultStanding;
            @VaultStanding.canceled -= instance.OnVaultStanding;
            @AimDown.started -= instance.OnAimDown;
            @AimDown.performed -= instance.OnAimDown;
            @AimDown.canceled -= instance.OnAimDown;
            @Fire.started -= instance.OnFire;
            @Fire.performed -= instance.OnFire;
            @Fire.canceled -= instance.OnFire;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @WeaponScroll.started -= instance.OnWeaponScroll;
            @WeaponScroll.performed -= instance.OnWeaponScroll;
            @WeaponScroll.canceled -= instance.OnWeaponScroll;
            @Reload.started -= instance.OnReload;
            @Reload.performed -= instance.OnReload;
            @Reload.canceled -= instance.OnReload;
        }

        public void RemoveCallbacks(IBaseMovementActions instance)
        {
            if (m_Wrapper.m_BaseMovementActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBaseMovementActions instance)
        {
            foreach (var item in m_Wrapper.m_BaseMovementActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BaseMovementActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BaseMovementActions @BaseMovement => new BaseMovementActions(this);

    // Cover
    private readonly InputActionMap m_Cover;
    private List<ICoverActions> m_CoverActionsCallbackInterfaces = new List<ICoverActions>();
    private readonly InputAction m_Cover_CoverMovement;
    private readonly InputAction m_Cover_ExitCover;
    private readonly InputAction m_Cover_VaultInCover;
    private readonly InputAction m_Cover_CoverAim;
    private readonly InputAction m_Cover_CoverLook;
    private readonly InputAction m_Cover_CoverShoot;
    public struct CoverActions
    {
        private @PlayerControls m_Wrapper;
        public CoverActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @CoverMovement => m_Wrapper.m_Cover_CoverMovement;
        public InputAction @ExitCover => m_Wrapper.m_Cover_ExitCover;
        public InputAction @VaultInCover => m_Wrapper.m_Cover_VaultInCover;
        public InputAction @CoverAim => m_Wrapper.m_Cover_CoverAim;
        public InputAction @CoverLook => m_Wrapper.m_Cover_CoverLook;
        public InputAction @CoverShoot => m_Wrapper.m_Cover_CoverShoot;
        public InputActionMap Get() { return m_Wrapper.m_Cover; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CoverActions set) { return set.Get(); }
        public void AddCallbacks(ICoverActions instance)
        {
            if (instance == null || m_Wrapper.m_CoverActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CoverActionsCallbackInterfaces.Add(instance);
            @CoverMovement.started += instance.OnCoverMovement;
            @CoverMovement.performed += instance.OnCoverMovement;
            @CoverMovement.canceled += instance.OnCoverMovement;
            @ExitCover.started += instance.OnExitCover;
            @ExitCover.performed += instance.OnExitCover;
            @ExitCover.canceled += instance.OnExitCover;
            @VaultInCover.started += instance.OnVaultInCover;
            @VaultInCover.performed += instance.OnVaultInCover;
            @VaultInCover.canceled += instance.OnVaultInCover;
            @CoverAim.started += instance.OnCoverAim;
            @CoverAim.performed += instance.OnCoverAim;
            @CoverAim.canceled += instance.OnCoverAim;
            @CoverLook.started += instance.OnCoverLook;
            @CoverLook.performed += instance.OnCoverLook;
            @CoverLook.canceled += instance.OnCoverLook;
            @CoverShoot.started += instance.OnCoverShoot;
            @CoverShoot.performed += instance.OnCoverShoot;
            @CoverShoot.canceled += instance.OnCoverShoot;
        }

        private void UnregisterCallbacks(ICoverActions instance)
        {
            @CoverMovement.started -= instance.OnCoverMovement;
            @CoverMovement.performed -= instance.OnCoverMovement;
            @CoverMovement.canceled -= instance.OnCoverMovement;
            @ExitCover.started -= instance.OnExitCover;
            @ExitCover.performed -= instance.OnExitCover;
            @ExitCover.canceled -= instance.OnExitCover;
            @VaultInCover.started -= instance.OnVaultInCover;
            @VaultInCover.performed -= instance.OnVaultInCover;
            @VaultInCover.canceled -= instance.OnVaultInCover;
            @CoverAim.started -= instance.OnCoverAim;
            @CoverAim.performed -= instance.OnCoverAim;
            @CoverAim.canceled -= instance.OnCoverAim;
            @CoverLook.started -= instance.OnCoverLook;
            @CoverLook.performed -= instance.OnCoverLook;
            @CoverLook.canceled -= instance.OnCoverLook;
            @CoverShoot.started -= instance.OnCoverShoot;
            @CoverShoot.performed -= instance.OnCoverShoot;
            @CoverShoot.canceled -= instance.OnCoverShoot;
        }

        public void RemoveCallbacks(ICoverActions instance)
        {
            if (m_Wrapper.m_CoverActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICoverActions instance)
        {
            foreach (var item in m_Wrapper.m_CoverActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CoverActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CoverActions @Cover => new CoverActions(this);
    public interface IBaseMovementActions
    {
        void OnWalk(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnCover(InputAction.CallbackContext context);
        void OnVaultStanding(InputAction.CallbackContext context);
        void OnAimDown(InputAction.CallbackContext context);
        void OnFire(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnWeaponScroll(InputAction.CallbackContext context);
        void OnReload(InputAction.CallbackContext context);
    }
    public interface ICoverActions
    {
        void OnCoverMovement(InputAction.CallbackContext context);
        void OnExitCover(InputAction.CallbackContext context);
        void OnVaultInCover(InputAction.CallbackContext context);
        void OnCoverAim(InputAction.CallbackContext context);
        void OnCoverLook(InputAction.CallbackContext context);
        void OnCoverShoot(InputAction.CallbackContext context);
    }
}
